### ISSUE TITLE
Add a --describe option

### ISSUE THREAD

**Issue by suve** [suve/vrms-rpm#2]
Package names rarely make it immediately apparent what a particular program or library does. It could be helpful to add a `--describe` option to the program, which, akin to how `--explain` lists licences, would list package descriptions.

For a minimal version, `--describe` and `--explain` could be exclusive. Ideally, both can be specified and used at the same time.

**Comment by AtelesPaniscus** [comment]
I have had a go at this.  See Pull Request #13.

**Comment by suve** [comment]
Solved by commit [`6e304c85a6a4f702f058d5e8632e4e0647dbec5c`](https://github.com/suve/vrms-rpm/commit/6e304c85a6a4f702f058d5e8632e4e0647dbec5c).
