### ISSUE TITLE
Licences missing from `good-licenses.txt`

### ISSUE THREAD

**Issue by girst** [suve/vrms-rpm#31]
Hi, on my system, the package `texlive-rsfs` shows as non-free, because its license is spelt `rsfs`, but your whitelist only has `Rsfs` (as spelt on the fedora wiki). In my own implementation I use `grep -w -i`, which works fine.

I also noticed `texlive-lm`, which is licensed `GFSL`. [GFSL](http://www.gust.org.pl/projects/e-foundry/licenses/GUST-FONT-SOURCE-LICENSE.txt/view) is basically LaTeX' LPPL, which Fedora considers 'free', but removes clause 6.a.

**Comment by girst** [comment]
While we are at it: L190 is `pubkey` -- That's a hack for `gpg-pubkey` non-packages, isn't it? That will slightly inflate the 'free packages' count.

Also, the license `Bitstream vera` (used by e.g. `texlive-bera`) has the same case-sensitivity issue.

**Comment by suve** [comment]
Regarding the `texlive` fonts licenses, I've opened a bug report in Red Hat Bugzilla some time ago: https://bugzilla.redhat.com/show_bug.cgi?id=1539286

The list of licences was mostly copied verbatim from the [Fedora wiki licensing page](https://fedoraproject.org/wiki/Licensing:Main#Good_Licenses). I think `pubkey` should stay, or maybe we could consider adding some kind of "not applicable" category apart form "free" & "non-free".

All that being said, there are two license tags missing from the list: `EPL-1.0` and `EPL-2.0`, which were added pretty recently (March 28).

**Comment by suve** [comment]
Closing this issue as the list of licences has been updated multiple times (a9dd52686f16664559a9fb33e06e3c3a7974ca8a, 91a3fb5dfb58ace677aab0f134bf877ab7553dc1, 2f66ae8f19479f8c75524a76dc9769a0a452b693) since it was originally posted, and I consider it resolved.
