### ISSUE TITLE
Update Danish translation to version 2.0

### ISSUE THREAD

**Issue by suve** [suve/vrms-rpm#33]
Version `1.2` of **vrms-rpm** had a Danish translation. Given the major overhaul of the program for version `2.0`, this translation can no longer be used. It'd be awesome if we could update the translation (or create an entirely new one) for the new version.

Files containing the old translation:
- `lang/outdated/da.po`
- `man/outdated/da.man`

New text (in English) to be translated:
- `lang/en.po`
- `man/en.man`

**Comment by klan** [comment]
I'll take this one :)

**Comment by suve** [comment]
Solved by #65.
