### ISSUE TITLE
Update German translation for version 2.0

### ISSUE THREAD

**Issue by suve** [suve/vrms-rpm#34]
Version `1.2` of **vrms-rpm** had a German translation. Given the major overhaul of the program for version `2.0`, this translation can no longer be used. It'd be awesome if we could update the translation (or create an entirely new one) for the new version.

Files containing the old translation:
- `lang/outdated/de.po`
- `man/outdated/de.man`

New text (in English) to be translated:
- `lang/en.po`
- `man/en.man`

**Comment by msdeibel** [comment]
I'll take this one :)

**Comment by pille1842** [comment]
> I'll take this one :)

Are you still on this? I can give it a go, too.

**Comment by msdeibel** [comment]
Already added PR #45

**Comment by pille1842** [comment]
Ha, didn't see that.

**Comment by suve** [comment]
Solved by #45.
