### ISSUE TITLE
Update Spanish translation for version 2.0

### ISSUE THREAD

**Issue by suve** [suve/vrms-rpm#36]
Version `1.2` of **vrms-rpm** had a Spanish translation. Given the major overhaul of the program for version `2.0`, this translation can no longer be used. It'd be awesome if we could update the translation (or create an entirely new one) for the new version.

Files containing the old translation:
- `lang/outdated/es.po`
- `man/outdated/es.man`

New text (in English) to be translated:
- `lang/en.po`
- `man/en.man`

**Comment by mroutis** [comment]
@suve, I'll take it!

**Comment by jobagcha** [comment]
I can help help you translating to Spanish

**Comment by mroutis** [comment]
there's already a PR, you can review @jobagcha : https://github.com/suve/vrms-rpm/pull/48

**Comment by suve** [comment]
Solved by #48.
