### ISSUE TITLE
Update Indonesian translation for version 2.0

### ISSUE THREAD

**Issue by suve** [suve/vrms-rpm#38]
Version `1.2` of **vrms-rpm** had an Indonesian translation. Given the major overhaul of the program for version `2.0`, this translation can no longer be used. It'd be awesome if we could update the translation (or create an entirely new one) for the new version.

Files containing the old translation:
- `lang/outdated/id.po`
- `man/outdated/id.man`

New text (in English) to be translated:
- `lang/en.po`
- `man/en.man`

**Comment by harkce** [comment]
I can take this

**Comment by suve** [comment]
Solved by Pull Request #69.
