### ISSUE TITLE
Update Italian translation for version 2.0

### ISSUE THREAD

**Issue by suve** [suve/vrms-rpm#39]
Version `1.2` of **vrms-rpm** had an Italian translation. Given the major overhaul of the program for version `2.0`, this translation can no longer be used. It'd be awesome if we could update the translation (or create an entirely new one) for the new version.

Files containing the old translation:
- `lang/outdated/it.po`
- `man/outdated/it.man`

New text (in English) to be translated:
- `lang/en.po`
- `man/en.man`

**Comment by suve** [comment]
This issue relates to the `devel-2.0` branch. If you're using the command-line client, use:
```
git checkout devel-2.0
```
For a GUI client, you'll probably find this option somewhere in a "branches" menu.

**Comment by platipo** [comment]
@suve you can close both #47 and this issue.

**Comment by suve** [comment]
Right. @platipo sorry for not doing this sooner.

Solved by PR #57.
