### ISSUE TITLE
Update Portuguese translation for version 2.0

### ISSUE THREAD

**Issue by suve** [suve/vrms-rpm#41]
Version `1.2` of **vrms-rpm** had a Portuguese translation. Given the major overhaul of the program for version `2.0`, this translation can no longer be used. It'd be awesome if we could update the translation (or create an entirely new one) for the new version.

Files containing the old translation:
- `lang/outdated/pt.po`
- `man/outdated/pt.man`

New text (in English) to be translated:
- `lang/en.po`
- `man/en.man`

**Comment by edsoncelio** [comment]
@suve can i work on that issue? :)

**Comment by suve** [comment]
Sure! If you have any questions or aren't sure about something, feel free to ask.

**Comment by suve** [comment]
Solved by #46.
