### ISSUE TITLE
Update Turkish translation for version 2.0

### ISSUE THREAD

**Issue by suve** [suve/vrms-rpm#42]
Version `1.2` of **vrms-rpm** had a Turkish translation. Given the major overhaul of the program for version `2.0`, this translation can no longer be used. It'd be awesome if we could update the translation (or create an entirely new one) for the new version.

Files containing the old translation:
- `lang/outdated/tr.po`
- `man/outdated/tr.man`

New text (in English) to be translated:
- `lang/en.po`
- `man/en.man`

**Comment by bureken** [comment]
Hello, I would like to work on this.

**Comment by suve** [comment]
Feel free to take this. Note that you should base your work on the `devel-2.0` branch, not `master`.

**Comment by suve** [comment]
Solved by #60.
