### ISSUE TITLE
vrms-rpm counts packages once for each version installed

### ISSUE THREAD

**Issue by nemobis** [suve/vrms-rpm#75]
Thank you for this very informative and educational vrms!

I suppose this is correct, literally speaking, but the percentage feels a bit less fair when every kernel package is counted three times. :) Feel free to close as invalid if this is intended.

```
$ LANG=en_GB vrms-rpm
2176 free packages (98.1% of total)
44 non-free packages (1.9% of total)
 - atmel-firmware
 - fedora-logos
 - gobject-introspection
 - google-chrome-stable
 - ipw2100-firmware
 - ipw2200-firmware
 - iwl100-firmware
 - iwl1000-firmware
 - iwl105-firmware
 - iwl135-firmware
 - iwl2000-firmware
 - iwl2030-firmware
 - iwl3160-firmware
 - iwl3945-firmware
 - iwl4965-firmware
 - iwl5000-firmware
 - iwl5150-firmware
 - iwl6000-firmware
 - iwl6000g2a-firmware
 - iwl6000g2b-firmware
 - iwl6050-firmware
 - iwl7260-firmware
 - kernel
 - kernel
 - kernel
 - kernel-core
 - kernel-core
 - kernel-core
 - kernel-devel
 - kernel-devel
 - kernel-devel
 - kernel-modules
 - kernel-modules
 - kernel-modules
 - kernel-modules-extra
 - kernel-modules-extra
 - kernel-modules-extra
 - libertas-usb8388-firmware
 - librados2
 - librbd1
 - linux-firmware
 - linux-firmware-whence
 - lttng-ust
 - microcode_ctl
$ rpm -qa | grep kernel-core
kernel-core-5.9.16-200.fc33.x86_64
kernel-core-5.10.6-200.fc33.x86_64
kernel-core-5.10.7-200.fc33.x86_64
```

**Comment by suve** [comment]
I thought about this and here's my stance: Software licenses change sometimes. It can be a proprietary program going open-source, but it can also be something like MongoDB switching to SSPL (which the OSI does not consider free). As such, it makes sense for "duplicate" packages to be counted separately, as there is a (however miniscule) chance that one version may be deemed free, but the other one not.

Thanks for bringing this to my attention, though. I think it would be a good idea to add a mechanism to the program where it detects duplicate packages, and when listing them, prints the version-release info as well, to reduce ambiguity.

**Comment by nemobis** [comment]
Makes sense, thanks for the thoughtful reply! Feel free to close this 
issue if you want.

**Comment by suve** [comment]
@nemobis today's commits to `trunk` add handling of duplicate packages: when duplicates are detected, *vrms-rpm* will print the `epoch:version-release.arch` information to eliminate ambiguity as to which package it's describing. If you have some time to spare, please test this out and report any bugs you encounter, or suggestions you may have.

**Comment by Ricky-Tigg** [comment]
_nemobis_ |"_vrms-rpm counts packages once for each version installed_".

Hello. Not only. **Fake packages with GPG keys** are taken in account in the query. The rpm utility does so when `rpm -qa` is invoked. In a system where such packages can be found, their presence can be attested with `vrms-rpm --list all | grep ' gpg-pubkey$'`.

**Comment by suve** [comment]
*vrms-rpm* v2.3 was released this Sunday; this release includes the duplicate-detection behaviour (plus the `--evra` option) and special handling for `gpg-pubkey` packages. Closing this as completed.
