### ISSUE TITLE
Numbers of installed packages reported by `vrms-rpm --list all` and `vrms-rpm --list none` as total sum, differ from each other

### ISSUE THREAD

**Issue by Ricky-Tigg** [suve/vrms-rpm#88]
Hello. In v. 2.2 the numbers of installed packages reported by `vrms-rpm --list all` and `vrms-rpm --list none` as total sum, differ from each other.
```
$ vrms-rpm --list all | wc -l
1999
$ vrms-rpm --list none
1888 free packages (94.6% of total)
109 non-free packages (5.4% of total)
```
`vrms-rpm --list none`'s output | **total sum** of installed packages: _1997_.

Worth noting: numbers of installed packages reported by `rpm -qa` and `dnf rq --installed` in IBM's Red Hat and Fedora OSs may differ from each other due to the fact that the rpm utility takes in account **fake packages with GPG keys**. Illustrations:
```
$ rpm -qa | wc -l
1991
$ dnf rq --installed | wc -l
1989
$ diff <(dnf rq --installed --nvr) <(rpm -qa --qf '%{nvr}\n') | grep '^> gpg-pubkey-' | wc -l
2
```
It appears that `all` for `vrms-rpm --list` behaves as `rpm -qa` does. 
```
$ vrms-rpm --list all | grep ' gpg-pubkey$' | wc -l
2
```
This ability to count fake packages appears to be useful, thought as demonstrated here, as a dedicated option so it could be queried on demand. Yet here the non-equality of numbers of installed packages reported by `vrms-rpm --list all` and `vrms-rpm --list none` as total sum, indicates an issue.

**Comment by suve** [comment]
The two summary lines showing the number of free/non-free packages are printed in both `--list none` and `--list all` mode:
```
$ vrms-rpm --list all
XXX free packages (xx.x% total)
- package1
- package2
[...]
YYY non-free packages (yy.y% total)
- package3
- package4
[...]
```
Because of these two lines, running `vrms-rpm --list-all | wc -l` produces a number that's off by 2 when compared to the sum of `XXX + YYY`.

**Comment by Ricky-Tigg** [comment]
That's what a poor analyse can do; i put myself on a wrong track. `expr $(vrms-rpm --list all | wc -l) - 2` will do.
